/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.ui;

import com.adobe.acrobat.Viewer;
import com.eps.studydoctor.UI.FileExplorer;
import com.org.classes.BookReader;
import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListModel;
import com.org.classes.PrintTree;
import java.util.Iterator;
import javax.swing.JFrame;

/**
 *
 * @author EVAN
 */
public class StudyBooks extends javax.swing.JInternalFrame {

    ListModel<String> model;

    /**
     * Creates new form StudyBooks
     */
    public StudyBooks() {
//        try {
            initComponents();
//            jPanel1.setLayout(new BorderLayout());
//            viewer = new Viewer();
//            createReader(fileName);
//            jPanel1.add(viewer, BorderLayout.CENTER);

//            jList1.setModel(model);
//            jList1.setListData(listData);
            // viewer.
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
    }
    private Viewer viewer;
    FileInputStream fis;
    String fileName;
    static String filePath;
    static FileWriter writer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jScrollPane2.setViewportView(jList1);

        jLabel1.setText("BOOKS");

        jMenu1.setText("File");

        jMenuItem1.setText("Add a book");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(695, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        FileExplorer explore = new FileExplorer(null, true);
        explore.setVisible(true);
        filePath = explore.file_.getAbsolutePath();
        fileName = explore.file_.getName();

    }//GEN-LAST:event_jMenuItem1ActionPerformed
    void createReader(String fileName) throws FileNotFoundException, Exception {
        fis = new FileInputStream(fileName);
        viewer.setDocumentInputStream(fis);

    }

    static void addBook() throws IOException {
//      FileExplorer explore = new FileExplorer(null, true);
//      explore.setVisible(true);
//      File listLocation = new File("Lists.txt");
//      filePath = FileExplorer.file_.toString() ;
//      writer = new FileWriter(listLocation);
//      writer.write(filePath);
//      writer.flush();
//      writer.close();
// 

    }

    public static void main(String args[]) {
        FileExplorer explorer = new FileExplorer(null, true);
        explorer.setVisible(true);
        filePath = explorer.file_.toString();
        BookReader reader = new BookReader(filePath);
//        StudyBooks studybooks = new StudyBooks();
//        studybooks.getContentPane().add(reader);
//        studybooks.setVisible(true);
        Welcome welcome = new Welcome();
       welcome.getContentPane().add(reader);
      welcome.setVisible(true);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
