/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.classes;

import com.adobe.acrobat.Viewer;
import java.awt.BorderLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class BookReader extends javax.swing.JPanel {

    private Viewer viewer;
    

    /**
     * Creates new form BookReader
     */
    public BookReader() {
        initComponents();
    }

    public BookReader(String fileName) {
        //  initComponents();
        FileInputStream fis = null;
        try {
            this.setLayout(new BorderLayout());
            viewer = new Viewer();
            fis = new FileInputStream(fileName);
            viewer.setDocumentInputStream(fis);
           this.add(viewer, BorderLayout.CENTER);
            viewer.activate();
            
             fis.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public static void main(String args []){
        BookReader bookReader = new BookReader("C:\\Users\\kolis\\Desktop\\My Curriculum Vitae.pdf");
        JFrame f = new JFrame();
        f.setSize(1024,768);
        f.setVisible(true);
        f.getContentPane().add(bookReader);
        
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
